#!/usr/bin/env bash

## VARIABLES
THIS_DIR=$(cd "$(dirname "$0")"; pwd)
Y_DATE=$(date -d 'yesterday' '+%y%m%d')
TDBOT="https://valtman.name/files/telegram-bot-$Y_DATE-nightly-linux"

## Print Colorful
# Print text in red
prtred() {
	printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
# Print text in green
prtgrn() {
	printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
# Print text in brown
prtbrown() {
	printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}

# autolauncher
autolaunchmod() {
	while true ; do
		for tablighgar in bot-*.lua ; do
			tab="${tablighgar%.*}"
			ltab="${tab/-/ }"
			tmux kill-session -t $tab
			rm -rf .telegram-bot/$tab/files
			for tg in .telegram-bot/$tab/data/* ; do
				rm -rf $tg/*
			done
			TMUX= tmux new-session -d -s $tab "./$ltab"
			tmux detach -s $tab
		done
		echo -e " \n\e[1;32mربات ها راه اندازی شدند << \e[1;34m| Naji |\e[1;32m>> Bots are Running\n\e[0;39;49m"
		sleep 1200
	done 
}
# clear a bot
clear() {
	rm -rf .telegram-bot/bot-"$1"
	rm -rf bot-"$1".lua
	redis-cli --raw keys "bot"$1* | xargs redis-cli del
	prtgrn '
     ربات شماره '$1' با موفقیت حذف شد <<
  >> Bot number '$1' seccessfuly deleted.
 '
}
# install Bot
install() {
	prtgrn '
         آیا قصد نصب پیش نیاز های ربات تبلیغ‌گر را دارید؟ بله|خیر <<
  >> Do you want to install Essentials of Bot? (Y/N):
 '
	read -rp ' ' install
	case "$install" in
    Y|y|بله)
		prtgrn '
         telegram-bot بارگیری <<
 >> Fetching $TDBOT
 '
		wget "$TDBOT" -O telegram-bot
		chmod +x telegram-bot
		prtgrn '
     ارتقای اطلاعات قدیمی <<
 >> Updating old packages
 '
		sudo apt-get -y update && sudo apt-get -y upgrade 
		prtgrn '
        نصب بسته های پیش نیازی <<
 >> Installing Essentials packages
 '
		sudo apt-get --force-yes install git wget screen tmux libconfig9 libevent-dev libjansson4 libstdc++6 lua-socket lua5.2 liblua5.2 make unzip redis-server software-properties-common g++ libconfig++-dev
		sudo apt-get -y update && sudo apt-get -y upgrade
		sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -y update && sudo apt-get --force-yes install gcc-4.9 g++-4.9 && sudo update-alternatives —install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 —slave /usr/bin/g++ g++ /usr/bin/g++-4.9
		prtgrn '
 ارتقای بسته های نصب شده <<
 >> Updating packages
 '
		sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt-get -y autoremove
		prtgrn '
      redis راه اندازی مجدد  <<
 >> Restarting redis service
 '
		sudo service redis-server restart
		prtgrn '
      همگام سازی با جدیدترین نسخه تبلیغ‌گر << 
 >> Fetching latest Bot source code
 '
		git pull
		prtgrn '
      نصب پیش نیاز های ربات تبلیغ‌گر با موفقیت انجام شد << 
 >> Essentials of Tablighgar Bot successfully installed!
 '
		printf '\e[1;33mراه اندازی کنید\e[1;32m ./bot ID \e[1;33mربات تبلیغ‌گر خود را با دستور <<\e[1;33m%s\n >>Run Your bot with\e[1;32m ./bot ID\e[0;39;49m%s\n'
    ;;
    N|n|خیر)
		prtbrown '
        لغو عملیات
 Canceling the operation
 '
    ;;
    *)
		prtred '
    دستور اشتباه
  Wrong command
 '
		install
    ;;
	esac
}
# make config file
make_config() {
	mkdir -p "$THIS_DIR"/.telegram-bot/bot-"$1"
	cfg="$THIS_DIR"/.telegram-bot/bot-$1/bot.cfg
	bot="$THIS_DIR"/bot-$1.lua
	if [[ ! -f $cfg ]]; then
		echo "#Coded by Naji
default_profile = \"bot$1\";
bot$1 = {
	config_directory = \"$THIS_DIR/.telegram-bot/bot-$1\";
	test = false;
	use_file_db = true;
	use_file_gc = true;
	file_readable_names = true;
	use_secret_chats = false;
	use_chat_info_db = true;
	use_message_db = true;
	verbosity = 0;
	lua_script = \"$THIS_DIR/bot-$1.lua\";
};" >> $cfg
	fi
	if [[ ! -f $bot ]]; then
		cat bot.lua >> bot-$1.lua
		sed -i 's/BOT-ID/'$1'/g' bot-$1.lua
	fi
}
# login
login() {
	clear $1
	make_config $1
	prtgrn '
	 شماره تلفن تبلیغ‌گر مورد نظر را وارد نمایید <<
>> Inter the Advertiser bot phone number: 
 '
	read -rp ' ' number
	num=${number/+/00}
	./telegram-bot -c "$THIS_DIR"/.telegram-bot/bot-$1/bot.cfg --login --phone="${num// /}"
	run $1
}
# run a bot
run() {
	./telegram-bot -c "$THIS_DIR"/.telegram-bot/bot-$1/bot.cfg 
}
# help and usage
usage() {
	printf "\e[1;36m"
	cat <<EOF
  
                    $0 [موارد استفاده  : [گزینه ها <<
                                        : گزینه ها
        شماره             راه اندازی ربات با این شماره 
    نصب پیش نیاز های ربات تبلیغ‌گر           install
                   نمایش این متن            help
   راه‌اندازی تمام ربات ها هر 20 دقیقه          autolaunch
                  
>> Usage: $0 [options]
    Options:
      autolaunch        Launch all bots every 20 mins
      NUMBER            Start bot whit this ID number
      install           Install of Bot
	  login [id]        login to bot
      help              Print this message
	  clr [id]          clean data of Bot     
EOF
	printf "%s\n\e[0;39;49m"
}
## MAIN ------------------------------------------------------------------------
# Make sure this script run inside Bot directory
cd "$THIS_DIR" || exit
case $1 in
	install)
		install
	;;
	autolaunch)
		tmux kill-session -t autolaunch
		tmux new-session -s autolaunch "bash bot autolaunchmod"
	;;
	autolaunchmod)
		autolaunchmod
	;;
	help)
		usage
	;;
	clr)
		if [ -z "$2" ]; then
			prtgrn '
	   : شماره شناسه تبلیغ‌گری که می‌خواهید پاک کنید را وارد کنید  <<
  >> Inter the BOT-ID,that you wanna delete :
 '
			read -rp ' ' ID
			clear "$ID"
		else
			clear "$2"
		fi
	;;
	login)
		if [ -z "$2" ]; then
			prtgrn '
       : شماره شناسه تبلیغ‌گری که می‌خواهید  وارد شوید را وارد کنید  <<
  >> Inter the BOT-ID,that you wanna login :
 '
			read -rp ' ' ID
			login $ID
		else
			login "$2"
		fi
	;;
	*)
		if [[ "$1" =~ ^[0-9]+$ ]] ; then
			if [ -a "$THIS_DIR"/bot-"$1".lua ]; then
				make_config $1
				run $1
			else
				login $1
			fi
		else
			usage
		fi
	;;
esac
